### ISSUE TITLE
🚩 Landing Page

### ISSUE THREAD

**Issue by aarvinr** [aarvinr/checkpoint#2]
The primary landing page for the website.

- [ ] Hero tagline, description
- [ ] Call-to-action buttons
- [ ] Screenshot/interactive demo
- [ ] Feature list and/or sections
